### login
POST http://localhost:8888/login

### get all books
GET http://localhost:8888/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEwMjQ0MDF9.yeadQ82QGVgrxiaqlPIx_1XNcQEJflYtYcdOafpJ-GQ

### create new book
POST  http://localhost:8888/books
Content-Type: application/json

{
	"id":"3",
	"title":"title",
	"author":"author"
}

### delete a book
DELETE  http://localhost:8888/books/4